apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: turbofan-api-monitor
  namespace: default
  labels:
    app: turbofan-api
spec:
  selector:
    matchLabels:
      app: turbofan-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s