apiVersion: v1
kind: Service
metadata:
  name: turbofan-api-service
  labels:
    app: turbofan-api
spec:
  type: LoadBalancer
  selector:
    app: turbofan-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000